### ISSUE TITLE
Weights link

### ISSUE THREAD

**Issue by youssefmohana** [IPMI-NWU/GD-ViG#1]
@SX-SS  Weights link not working can please afford link on drive please Thanks for help

**Comment by youssefmohana** [comment]
iam from Egypt so idont have chinese  phone number so can you provide it as google drive link Thanks for help  

gmail:**youssefmohana7@gmail.com**

**Comment by SX-SS** [comment]
Thank you for your interest in this work. Here is a link to the model weights on google drive.
https://drive.google.com/drive/folders/1mIUxiqGHdDmnXm2xDH5_8feNEW9LZi6s?usp=drive_link

**Comment by youssefmohana** [comment]
Thanks for help

**Comment by youssefmohana** [comment]
Thanks for help
